name: Build and Publish Release to PYPI

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish-modelscan:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0 # Necessary to get tags
      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: "3.9"
      - uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Get Release Version
        uses: mtkennerly/dunamai-action@9cd4531c0025990c4b81719270f328f459834d12 # v1.3.0
        with:
          env-var: MODELSCAN_VERSION
          args: --style semver --format "{base}"
      - name: Set Package Version
        run: |
          echo "__version__ = '$MODELSCAN_VERSION'" > modelscan/_version.py
          poetry version $MODELSCAN_VERSION
      - name: Build Package
        run: |
          poetry build
      - name: Publish Package to PYPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.MODELSCAN_PYPI_API_TOKEN }}
          poetry publish
